package com.study.fldemo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.study.fldemo.dao.DatabaseBean;

import com.study.fldemo.dao.DatabaseBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig databaseBeanDaoConfig;

    private final DatabaseBeanDao databaseBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        databaseBeanDaoConfig = daoConfigMap.get(DatabaseBeanDao.class).clone();
        databaseBeanDaoConfig.initIdentityScope(type);

        databaseBeanDao = new DatabaseBeanDao(databaseBeanDaoConfig, this);

        registerDao(DatabaseBean.class, databaseBeanDao);
    }
    
    public void clear() {
        databaseBeanDaoConfig.clearIdentityScope();
    }

    public DatabaseBeanDao getDatabaseBeanDao() {
        return databaseBeanDao;
    }

}
